"""Common contest identifiers from the WA7BNM Cabrillo-name list.

The selector submits the code; a custom value remains available for contests
added to the published list after this application is released.
"""

CONTEST_CALENDAR_URL = "https://www.contestcalendar.com/cabnames.php"

CONTESTS = [
    ("TEST", "HamDash Test Contest"),
    ("10-10-SPRINT", "10-10 Int. 10-10 Day Sprint"),
    ("10-10-FALL-DIGITAL", "10-10 Int. Fall Contest, Digital"),
    ("10-10-SUMMER-PHONE", "10-10 Int. Summer Contest, SSB"),
    ("10-10-WINTER-PHONE", "10-10 Int. Winter Contest, SSB"),
    ("7QP", "7th Call Area QSO Party"),
    ("AL-QSO-PARTY", "Alabama QSO Party"),
    ("AADX-CW", "All Asian DX Contest, CW"),
    ("AADX-SSB", "All Asian DX Contest, Phone"),
    ("ARRL-10", "ARRL 10-Meter Contest"),
    ("ARRL-160", "ARRL 160-Meter Contest"),
    ("ARRL-FD", "ARRL Field Day"),
    ("ARRL-DIGI", "ARRL Inter. Digital Contest"),
    ("ARRL-DX-CW", "ARRL Inter. DX Contest, CW"),
    ("ARRL-DX-SSB", "ARRL Inter. DX Contest, SSB"),
    ("ARRL-VHF-JAN", "ARRL January VHF Contest"),
    ("ARRL-VHF-JUN", "ARRL June VHF Contest"),
    ("ARRL-RTTY", "ARRL RTTY Roundup"),
    ("ARRL-SCR", "ARRL School Club Roundup"),
    ("ARRL-VHF-SEP", "ARRL September VHF Contest"),
    ("ARRL-SS-CW", "ARRL Sweepstakes Contest, CW"),
    ("ARRL-SS-SSB", "ARRL Sweepstakes Contest, SSB"),
    ("ARRL-RR-CW", "ARRL Rookie Roundup, CW"),
    ("ARRL-RR-DIG", "ARRL Rookie Roundup, RTTY"),
    ("ARRL-RR-PH", "ARRL Rookie Roundup, SSB"),
    ("BARTG-RTTY", "BARTG HF RTTY Contest"),
    ("BARTG-SPRINT", "BARTG RTTY Sprint"),
    ("CQ-160-CW", "CQ 160-Meter Contest, CW"),
    ("CQ-160-SSB", "CQ 160-Meter Contest, SSB"),
    ("CQ-WPX-CW", "CQ WW WPX Contest, CW"),
    ("CQ-WPX-RTTY", "CQ WW RTTY WPX Contest"),
    ("CQ-WPX-SSB", "CQ WW WPX Contest, SSB"),
    ("CQ-WW-CW", "CQ Worldwide DX Contest, CW"),
    ("CQ-WW-RTTY", "CQ Worldwide DX Contest, RTTY"),
    ("CQ-WW-SSB", "CQ Worldwide DX Contest, SSB"),
    ("CQ-VHF-DIGI", "CQ Worldwide VHF Digital Contest"),
    ("CQ-VHF-SSBCW", "CQ Worldwide VHF SSB/CW Contest"),
    ("CQ-M", "CQ-M International DX Contest"),
    ("IARU-HF", "IARU HF World Championship"),
    ("NAQP-CW", "North American QSO Party, CW"),
    ("NAQP-RTTY", "North American QSO Party, RTTY"),
    ("NAQP-SSB", "North American QSO Party, SSB"),
    ("NA-SPRINT-CW", "North American Sprint, CW"),
    ("NA-SPRINT-RTTY", "North American Sprint, RTTY"),
    ("NA-SPRINT-SSB", "North American SSB Sprint Contest"),
    ("NEQP", "New England QSO Party"),
    ("MDC-QSO-PARTY", "Maryland-DC QSO Party"),
    ("PA-QSO-PARTY", "Pennsylvania QSO Party"),
    ("VA-QSO-PARTY", "Virginia QSO Party"),
    ("FCG-FQP", "Florida QSO Party"),
    ("NY-QSO-PARTY", "New York QSO Party"),
    ("NC-QSO-PARTY", "North Carolina QSO Party"),
    ("MRRC-OHQP", "Ohio QSO Party"),
    ("CA-QSO-PARTY", "California QSO Party"),
    ("COQP", "Colorado QSO Party"),
    ("GA-QSO-PARTY", "Georgia QSO Party"),
    ("IL-QSO-PARTY", "Illinois QSO Party"),
    ("IN-QSO-PARTY", "Indiana QSO Party"),
    ("NJQP", "New Jersey QSO Party"),
    ("QC-QSO-PARTY", "Quebec QSO Party"),
    ("SC-QSO-PARTY", "South Carolina QSO Party"),
    ("TN-QSO-PARTY", "Tennessee QSO Party"),
    ("TXQP", "Texas QSO Party"),
    ("VT-QSO-PARTY", "Vermont QSO Party"),
    ("WVQP", "West Virginia QSO Party"),
    ("WFD", "Winter Field Day"),
    ("SARTG-RTTY", "SARTG World Wide RTTY Contest"),
    ("RADIO-WW-RTTY", "Russian RTTY WW Contest"),
    ("WW-DIGI", "World Wide Digi DX Contest"),
]
